[build]
publish = "_site"
command = "DEBUG=* eleventy"

[[plugins]]
package = "@resoc/netlify-plugin-social-image"

  [plugins.inputs]
  templates_dir = "resoc-templates"
  open_graph_base_path = "/social-images"
  slug_to_image_data_mapping_file = "resoc-image-data.json"
